//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyAndConductorManager.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DutyAndConductorManager.Web.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activated successfully. Now you can set your password using the form below..
        /// </summary>
        public static string alert_activate_success {
            get {
                return ResourceManager.GetString("alert-activate-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now set your new password below..
        /// </summary>
        public static string alert_forgot_password_success {
            get {
                return ResourceManager.GetString("alert-forgot-password-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor Service Manager.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string button_activate_submit {
            get {
                return ResourceManager.GetString("button-activate-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear form.
        /// </summary>
        public static string button_admin_add_user_reset {
            get {
                return ResourceManager.GetString("button-admin-add-user-reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string button_admin_add_user_submit {
            get {
                return ResourceManager.GetString("button-admin-add-user-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New announcement.
        /// </summary>
        public static string button_admin_announcement_list_new_announcement {
            get {
                return ResourceManager.GetString("button-admin-announcement-list-new-announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string button_admin_edit_close {
            get {
                return ResourceManager.GetString("button-admin-edit-close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string button_admin_edit_submit {
            get {
                return ResourceManager.GetString("button-admin-edit-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string button_admin_user_list_new_user {
            get {
                return ResourceManager.GetString("button-admin-user-list-new-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string button_forgot_password_submit {
            get {
                return ResourceManager.GetString("button-forgot-password-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string button_sign_in_forgot_password {
            get {
                return ResourceManager.GetString("button-sign-in-forgot-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string button_sign_in_submit {
            get {
                return ResourceManager.GetString("button-sign-in-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string dialog_admin_add_user {
            get {
                return ResourceManager.GetString("dialog-admin-add-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string dialog_admin_edit_user {
            get {
                return ResourceManager.GetString("dialog-admin-edit-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string dialog_forgot_password {
            get {
                return ResourceManager.GetString("dialog-forgot-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string error_activate_compare_password {
            get {
                return ResourceManager.GetString("error-activate-compare-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string error_activate_password {
            get {
                return ResourceManager.GetString("error-activate-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long and contain 1 lowercase letter, 1 upper case letter, 1 special character and 1 numeric character.
        /// </summary>
        public static string error_activate_regex_password {
            get {
                return ResourceManager.GetString("error-activate-regex-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password is required.
        /// </summary>
        public static string error_activate_repeat_password {
            get {
                return ResourceManager.GetString("error-activate-repeat-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is required.
        /// </summary>
        public static string error_admin_add_user_birth_date {
            get {
                return ResourceManager.GetString("error-admin-add-user-birth-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string error_admin_add_user_email {
            get {
                return ResourceManager.GetString("error-admin-add-user-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string error_admin_add_user_first_name {
            get {
                return ResourceManager.GetString("error-admin-add-user-first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string error_admin_add_user_last_name {
            get {
                return ResourceManager.GetString("error-admin-add-user-last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required.
        /// </summary>
        public static string error_admin_add_user_role {
            get {
                return ResourceManager.GetString("error-admin-add-user-role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string error_admin_add_user_username {
            get {
                return ResourceManager.GetString("error-admin-add-user-username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string error_forgot_password_email {
            get {
                return ResourceManager.GetString("error-forgot-password-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string error_sign_in_password {
            get {
                return ResourceManager.GetString("error-sign-in-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string error_sign_in_username {
            get {
                return ResourceManager.GetString("error-sign-in-username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string label_activate_password {
            get {
                return ResourceManager.GetString("label-activate-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string label_activate_repeat_password {
            get {
                return ResourceManager.GetString("label-activate-repeat-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string label_admin_add_user_birth_date {
            get {
                return ResourceManager.GetString("label-admin-add-user-birth-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_admin_add_user_email {
            get {
                return ResourceManager.GetString("label-admin-add-user-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string label_admin_add_user_first_name {
            get {
                return ResourceManager.GetString("label-admin-add-user-first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is trained?.
        /// </summary>
        public static string label_admin_add_user_is_trained {
            get {
                return ResourceManager.GetString("label-admin-add-user-is-trained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string label_admin_add_user_last_name {
            get {
                return ResourceManager.GetString("label-admin-add-user-last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string label_admin_add_user_phone_number {
            get {
                return ResourceManager.GetString("label-admin-add-user-phone-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_admin_add_user_role {
            get {
                return ResourceManager.GetString("label-admin-add-user-role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string label_admin_add_user_username {
            get {
                return ResourceManager.GetString("label-admin-add-user-username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_admin_edit_user_email {
            get {
                return ResourceManager.GetString("label-admin-edit-user-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string label_admin_edit_user_first_name {
            get {
                return ResourceManager.GetString("label-admin-edit-user-first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active?.
        /// </summary>
        public static string label_admin_edit_user_is_active {
            get {
                return ResourceManager.GetString("label-admin-edit-user-is-active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is trained?.
        /// </summary>
        public static string label_admin_edit_user_is_trained {
            get {
                return ResourceManager.GetString("label-admin-edit-user-is-trained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string label_admin_edit_user_last_name {
            get {
                return ResourceManager.GetString("label-admin-edit-user-last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string label_admin_edit_user_password {
            get {
                return ResourceManager.GetString("label-admin-edit-user-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string label_admin_edit_user_phone_number {
            get {
                return ResourceManager.GetString("label-admin-edit-user-phone-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_admin_edit_user_role {
            get {
                return ResourceManager.GetString("label-admin-edit-user-role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_forgot_password_email {
            get {
                return ResourceManager.GetString("label-forgot-password-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string label_sign_in_password {
            get {
                return ResourceManager.GetString("label-sign-in-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string label_sign_in_username {
            get {
                return ResourceManager.GetString("label-sign-in-username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string nav_group_management {
            get {
                return ResourceManager.GetString("nav-group-management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement list.
        /// </summary>
        public static string nav_link_admin_announcement_list {
            get {
                return ResourceManager.GetString("nav-link-admin-announcement-list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        public static string nav_link_admin_user_list {
            get {
                return ResourceManager.GetString("nav-link-admin-user-list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string nav_link_dashboard {
            get {
                return ResourceManager.GetString("nav-link-dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement list.
        /// </summary>
        public static string page_title_admin_announcement_list {
            get {
                return ResourceManager.GetString("page-title-admin-announcement-list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        public static string page_title_admin_user_list {
            get {
                return ResourceManager.GetString("page-title-admin-user-list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string page_title_sign_in {
            get {
                return ResourceManager.GetString("page-title-sign-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password set successfully. You can now sign in to your account..
        /// </summary>
        public static string snackbar_activate_set_password_success {
            get {
                return ResourceManager.GetString("snackbar-activate-set-password-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string snackbar_admin_add_user_success {
            get {
                return ResourceManager.GetString("snackbar-admin-add-user-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data saved successfully.
        /// </summary>
        public static string snackbar_admin_edit_success {
            get {
                return ResourceManager.GetString("snackbar-admin-edit-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while trying to fetch user data.
        /// </summary>
        public static string snackbar_admin_edit_user_error_user_data {
            get {
                return ResourceManager.GetString("snackbar-admin-edit-user-error-user-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string text_activate_set_password {
            get {
                return ResourceManager.GetString("text-activate-set-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No announcements found.
        /// </summary>
        public static string text_admin_announcement_list_no_records {
            get {
                return ResourceManager.GetString("text-admin-announcement-list-no-records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string text_global_no {
            get {
                return ResourceManager.GetString("text-global-no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string text_global_yes {
            get {
                return ResourceManager.GetString("text-global-yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string th_admin_announcement_list_creation_date {
            get {
                return ResourceManager.GetString("th-admin-announcement-list-creation-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator name.
        /// </summary>
        public static string th_admin_announcement_list_creator_name {
            get {
                return ResourceManager.GetString("th-admin-announcement-list-creator-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string th_admin_announcement_list_id {
            get {
                return ResourceManager.GetString("th-admin-announcement-list-id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string th_admin_announcement_list_message {
            get {
                return ResourceManager.GetString("th-admin-announcement-list-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement type.
        /// </summary>
        public static string th_admin_announcement_list_type_name {
            get {
                return ResourceManager.GetString("th-admin-announcement-list-type-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string th_admin_user_list_birth_date {
            get {
                return ResourceManager.GetString("th-admin-user-list-birth-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string th_admin_user_list_email {
            get {
                return ResourceManager.GetString("th-admin-user-list-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string th_admin_user_list_first_name {
            get {
                return ResourceManager.GetString("th-admin-user-list-first-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string th_admin_user_list_id {
            get {
                return ResourceManager.GetString("th-admin-user-list-id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active?.
        /// </summary>
        public static string th_admin_user_list_is_active {
            get {
                return ResourceManager.GetString("th-admin-user-list-is-active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is trained?.
        /// </summary>
        public static string th_admin_user_list_is_trained {
            get {
                return ResourceManager.GetString("th-admin-user-list-is-trained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string th_admin_user_list_last_name {
            get {
                return ResourceManager.GetString("th-admin-user-list-last-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string th_admin_user_list_phone_number {
            get {
                return ResourceManager.GetString("th-admin-user-list-phone-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string th_admin_user_list_role {
            get {
                return ResourceManager.GetString("th-admin-user-list-role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string th_admin_user_list_username {
            get {
                return ResourceManager.GetString("th-admin-user-list-username", resourceCulture);
            }
        }
    }
}
